# Site settings
title: Mike Verdicchio
tagline: Currently learning React and Cassandra
email: mikeverdicchio@gmail.com
description: >
  Mike Verdicchio is a software engineer at Capital
  One Shopping and a computer engineering grad of
  the University of Virginia.
baseurl: ""
url: "https://mikeverdicchio.github.io/"

# Build settings
markdown: kramdown
include: ["_pages"]

# Data Collections
collections:
  experience:
    output: true
    permalink: /:collection/:path
  projects:
    output: true
    permalink: /:collection/:path
